DROP SCHEMA IF EXISTS photoGallery CASCADE;
CREATE SCHEMA IF NOT EXISTS photoGallery AUTHORIZATION sdc_user;

CREATE TABLE IF NOT EXISTS gallery (
  id INTEGER NULL AUTO_INCREMENT,
  isSuperhost VARCHAR NULL DEFAULT NULL,
  reviews BINARY NULL DEFAULT NULL,
  rating INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE IF NOT EXISTS homes (
  home_id INTEGER NULL AUTO_INCREMENT,
  city VARCHAR NULL DEFAULT NULL,
  usState VARCHAR NULL DEFAULT NULL,
  country VARCHAR NULL DEFAULT NULL,
  rating INT NULL DEFAULT NULL,
  superhost BINARY NULL DEFAULT NULL,
  photos INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (home_id)
);

CREATE TABLE IF NOT EXISTS photos (
  photo_id INTEGER NULL AUTO_INCREMENT,
  user_id INTEGER NULL ,
  photo_url VARCHAR NULL DEFAULT NULL,
  upload_date TIMESTAMP NULL DEFAULT NULL,
  caption VARCHAR NULL DEFAULT NULL,
  PRIMARY KEY (photo_id)
);

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER NULL AUTO_INCREMENT,
  username VARCHAR NULL DEFAULT NULL,
  email VARCHAR NULL DEFAULT NULL,
  hashed_password VARCHAR NULL DEFAULT NULL,
  ip VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (user_id)
);
-- ---
-- Foreign Keys
-- ---

ALTER TABLE `Home` ADD FOREIGN KEY (home_id) REFERENCES `gallery` (`id`);
ALTER TABLE `Home` ADD FOREIGN KEY (photos) REFERENCES `Photos` (`photo_id`);
ALTER TABLE `Photos` ADD FOREIGN KEY (user_id) REFERENCES `users` (`user_id`);
