
DROP SCHEMA IF EXISTS photoGallery CASCADE;
CREATE SCHEMA IF NOT EXISTS photoGallery AUTHORIZATION sdc_user;

CREATE TABLE IF NOT EXISTS gallery (
  id INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  isSuperhost VARCHAR NULL DEFAULT NULL,
  reviews BINARY NULL DEFAULT NULL,
  rating INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE Home (
  home_id INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  city VARCHAR NULL DEFAULT NULL,
  state VARCHAR NULL DEFAULT NULL,
  country VARCHAR NULL DEFAULT NULL,
  rating INT NULL DEFAULT NULL,
  superhost BINARY NULL DEFAULT NULL,
  photos INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (home_id)
);



CREATE TABLE Photos (
  photo_id INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  user_id INTEGER NULL DEFAULT NULL,
  photo_url VARCHAR NULL DEFAULT NULL,
  upload_date TIMESTAMP NULL DEFAULT NULL,
  caption VARCHAR NULL DEFAULT NULL,
  PRIMARY KEY (photo_id)
);


CREATE TABLE users (
  user_id INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  username VARCHAR NULL DEFAULT NULL,
  email VARCHAR NULL DEFAULT NULL,
  hashed_password VARCHAR NULL DEFAULT NULL,
  ip VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (user_id)
);